language: python
git:
  depth: 20
cache:
  pip: true
  directories:
    - $HOME/.cache/pipenv
matrix:
  include:
    - python: 3.4
      name: "Python 3.4 pytest (default linux)"
    - python: 3.5
      name: "Python 3.5 pytest (default linux)"
    - python: 3.6
      name: "Python 3.6 pytest & mypy type-checking (default linux)"
      env: RUN_MYPY=yes
    - python: 3.7
      name: "Python 3.7 pytest (ubuntu xenial)"
      dist: xenial
      sudo: true
    - os: osx
      cache:
      - $HOME/Library/Caches/pip
      osx_image: xcode10
      sudo: required
      language: generic
install:
  - pip install pipenv==11.10
  - pipenv install --three --dev Pipfile
script:
  - pipenv run pytest
  - if [[ "$RUN_MYPY" == "yes" ]]; then pipenv run ./tools/run-mypy; fi
after_success:
  - pip install codecov
  - codecov
