language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install pipenv==11.10
  - pipenv install --dev Pipfile
script:
  - pipenv run pytest
  - pipenv run pytest --pep8
  - pipenv run ./tools/run-mypy
after_success:
  - pip install codecov
  - codecov
