language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - os: osx
      cache:
      - $HOME/Library/Caches/pip
      osx_image: xcode10
      sudo: required
      language: generic
      install:
      - pip install pipenv==11.10
      - pipenv install --three --dev Pipfile
install:
  - pip install pipenv==11.10
  - pipenv install --dev Pipfile
script:
  - pipenv run pytest
  - pipenv run pytest --pep8
  - pipenv run ./tools/run-mypy
after_success:
  - pip install codecov
  - codecov
