blank_issues_enabled: true
contact_links:
  - name: Report broader Zulip issues (beyond Zulip-Terminal)
    about: Includes links to best-practices for filing bug reports, feature requests, security vulnerabilities and more.
    url: https://github.com/zulip/zulip/issues/new/choose
  - name: Not sure?
    about: 'Chat with us, using any of the Zulip clients, in #zulip-terminal on the Developer Community server (chat.zulip.org).'
    url: https://zulip.com/development-community
