name: "Cancel previous runs"
on: [push, pull_request]

jobs:
  cancel:
    name: Cancel previous runs
    runs-on: ubuntu-latest
    timeout-minutes: 3

    # Don't run this job for zulip/zulip-terminal pushes since we
    # want to run those jobs.
    if: ${{ github.event_name != 'push' || github.event.repository.full_name != 'zulip/zulip-terminal' }}

    steps:
      - name: Perform cancellation
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          workflow_id: 
            codeql-analysis.yml,
            lint-and-test.yml
          access_token: ${{ github.token }}
