STREAM_TOPIC_SEPARATOR = '▶'
# Used as a separator between messages and 'EDITED'
MESSAGE_CONTENT_MARKER = '▒'  # Options are '█', '▓', '▒', '░'
QUOTED_TEXT_MARKER = '░'
MESSAGE_HEADER_DIVIDER = '━'
CHECK_MARK = '✓'
